function initMenu()
  % create figure and panel on it
f = figure('deletefcn', 'clear global; close all;', ...
           'units','normalized','position',[0 0 1 1]);
% create a button (default style)
% Image panel, contien le boutton pour charger une image et les infos de cette image

in_file = "default.png";

global input;
input = imread(in_file);

%% TOP PANEL
hptop = uipanel(f, 'Title','Image','FontSize',12,...
             'Position',[0 .85 1 .15], 'Units', 'normalized');

%% FILE NAME
global filetxt;
filetxt = uicontrol(hptop,'Style','text',...
        'Units', 'normalized','Position',[0.27 .5 0.35 0.4],...
        'String',in_file);

%% FILE SIZE
global restxt;
restxt = uicontrol(hptop,'Style','text',...
        'Units', 'normalized','Position',[0.27 .1 0.35 0.4],...
        'String',mat2str(size(input)));
       
%% LOAD BUTTON 
load = uicontrol(hptop, 'Style', 'pushbutton', 'String', 'Load',...
        'Units', 'normalized','Position', [0.05 .1 0.2 0.8],...
        'Callback', @onLoad);

%% IMAGE PREVIEW
global preview;
preview = axes('parent', hptop, 'Units', 'normalized', 'position', [0.7 .0 0.30 1], ...
                      'handlevisibility', 'off', 'visible', 'off');
image(preview, input);

%% MID PANEL
hpmid = uipanel(f, 'Title','Options','FontSize',12,...
             'Position',[0 .60 1 .25], 'Units', 'normalized');

%% ENERGY FUNCTION CHOICE
bg1 = uibuttongroup(hpmid, 'units', 'normalized', 'position', [0 0 .25 1]);
gradientButton = uicontrol(bg1,'Style','radiobutton',...
                                  'String','Gradient',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.7 1 .2]);
hogButton = uicontrol(bg1,'Style','radiobutton',...
                                  'String','HoG',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.5 1 .2]);                                
other1Button = uicontrol(bg1,'Style','radiobutton',...
                                  'String','other1',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.3 1 .2]);
other2Button = uicontrol(bg1,'Style','radiobutton',...
                                'String','other2',...
                                'units', 'normalized', ...
                                'Position',[0 0.1 1 .2]);
              
%% ENERGY DISPLAY CHOICE
bg2 = uibuttongroup(hpmid, 'units', 'normalized', 'position', [0.25 .0 .25 1]);
EnergyButton = uicontrol(bg2,'Style','radiobutton',...
                                  'String','Energy',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.7 1 .2]);
EnergyFlowButton = uicontrol(bg2,'Style','radiobutton',...
                                  'String','EnergyFlow',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.5 1 .2]); 
%% ENEGY PREVIEW       
global EnergyPreview;
EnergyPreview = axes('parent', hpmid, 'Units', 'normalized', 'position', [0.5 .0 0.5 1], ...
                      'handlevisibility', 'off', 'visible', 'off');
                      imagesc(EnergyPreview, imgradient(rgb2gray(im2double(input)), 'sobel'));
                   
hpbot = uipanel(f, 'Title','Result','FontSize',12,...
             'Position',[0 0 1 .60], "Units", 'normalized');    
        
end