function initMenu()
  % create figure and panel on it
f = figure('deletefcn', 'clear global; close all;', ...
           'units','normalized','position',[0 0 1 1]);
% create a button (default style)
% Image panel, contien le boutton pour charger une image et les infos de cette image

in_file = 'default.png';

global input;
input = imread(in_file);

%% TOP PANEL
hptop = uipanel(f, 'Title','Image','FontSize',12,...
             'Position',[0 .85 1 .15], 'Units', 'normalized');

%% FILE NAME
global filetxt;
filetxt = uicontrol(hptop,'Style','text',...
        'Units', 'normalized','Position',[0.27 .5 0.35 0.4],...
        'String',in_file);

%% FILE SIZE
global restxt;
restxt = uicontrol(hptop,'Style','text',...
        'Units', 'normalized','Position',[0.27 .1 0.35 0.4],...
        'String',mat2str(size(input)));
       
%% LOAD BUTTON 
load = uicontrol(hptop, 'Style', 'pushbutton', 'String', 'Load',...
        'Units', 'normalized','Position', [0.05 .1 0.2 0.8],...
        'Callback', @onLoad);

%% IMAGE PREVIEW
global preview;
preview = axes('parent', hptop, 'Units', 'normalized', 'position', [0.7 .0 0.30 1]);
imagesc(preview, input);

%% MID PANEL
hpmid = uipanel(f, 'Title','Options','FontSize',12,...
             'Position',[0 .60 1 .25], 'Units', 'normalized');

%% ENERGY FUNCTION CHOICE
global EnergyFcn;
EnergyFcn = 'Gradient';
bg1 = uibuttongroup(hpmid, 'units', 'normalized', ...
                    'position', [0 0 .25 1], ...
                    'SelectionChangedFcn', @onEnergyFcn);
gradientButton = uicontrol(bg1,'Style','radiobutton',...
                                  'String','Gradient',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.7 1 .2], ...
                                  'selected', 'on');
hogButton = uicontrol(bg1,'Style','radiobutton',...
                                  'String','HoG',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.5 1 .2]);                                
other1Button = uicontrol(bg1,'Style','radiobutton',...
                                  'String','other1',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.3 1 .2]);
other2Button = uicontrol(bg1,'Style','radiobutton',...
                                'String','other2',...
                                'units', 'normalized', ...
                                'Position',[0 0.1 1 .2]);
              
%% ENERGY DISPLAY CHOICE
global EnergyDisp;
EnergyDisp = 'Energy';
bg2 = uibuttongroup(hpmid, 'units', 'normalized', ...
                    'position', [0.25 .0 .25 1], ...
                    'SelectionChangedFcn', @onEnergyDisp);
EnergyButton = uicontrol(bg2,'Style','radiobutton',...
                                  'String','Energy',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.7 1 .2], ...
                                  'selected', 'on');
EnergyFlowButton = uicontrol(bg2,'Style','radiobutton',...
                                  'String','EnergyFlow',...
                                  'units', 'normalized', ...
                                  'Position',[0 0.5 1 .2]); 
%% ENEGY PREVIEW     
global energy;
energy = imgradient(rgb2gray(im2double(input)), 'sobel');
  
global EnergyPreview;
EnergyPreview = axes('parent', hpmid, 'Units', 'normalized', 'position', [0.5 .0 0.5 1]);
                      imagesc(EnergyPreview, energy);
    
%% BOTTOM PANEL    
hpbot = uipanel(f, 'Title','Result','FontSize',12,...
             'Position',[0 0 1 .60], 'Units', 'normalized');  
           
%% RUN BUTTON 
load = uicontrol(hpbot, 'Style', 'pushbutton', 'String', 'Run',...
        'Units', 'normalized','Position', [0.05 .85 0.12 0.10],...
        'Callback', @onRun);
        
%% STEP BUTTON 
load = uicontrol(hpbot, 'Style', 'pushbutton', 'String', 'Step',...
        'Units', 'normalized','Position', [0.18 .85 0.12 0.10],...
        'Callback', @onStep);
        
%% SAVE BUTTON 
load = uicontrol(hpbot, 'Style', 'pushbutton', 'String', 'Save',...
        'Units', 'normalized','Position', [0.05 .73 0.25 0.10],...
        'Callback', @onSave);
  
 
%% WIDTH SLIDER
hslider = uicontrol ( hpbot,               ...
         'style', 'slider',                ...
         'string', 'New Width',            ...
         'Units', 'normalized',            ...
         'position', [0.05, 0.45, 0.25, 0.1], ...
         'min', 1,                         ...
         'max', 50,                        ...
         'value', 10,                      ...
         'callback', ''          ...
       ); 
 
%% HEIGHT SLIDER
hslider = uicontrol ( hpbot,               ...
         'style', 'slider',                ...
         'string', 'New Height',           ...
         'Units', 'normalized',            ...
         'position', [0.05, 0.15, 0.25, 0.1], ...
         'min', 1,                         ...
         'max', 50,                        ...
         'value', 10,                      ...
         'callback', ''          ...
       );
       
%% RESULT PREVIEW
global result;
result = input;

global ResultPreview;
ResultPreview = axes('parent', hpbot, 'Units', 'normalized', 'position', [0.40 .0 0.6 1]);
imagesc(ResultPreview, result);
end